### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by matjam** [bottlepy/bottle-inject#4]
Following your example, I get this:

    Traceback (most recent call last):
      File "./outbreak-console", line 64, in <module>
        injector = bottle_app.install('bottle.ext.inject:Plugin')
      File "/usr/local/lib/python2.7/dist-packages/bottle-0.12.8-py2.7.egg/bottle.py", line 715, in install
        raise TypeError("Plugins must be callable or implement .apply()")
    TypeError: Plugins must be callable or implement .apply()

I'm sure it's something easy but it's not obvious to me.

**Comment by monadique** [comment]
Hi @matjam. 

I slightly adapted @defnull's original example. It should work this way:
```python
import sqlite3

from bottle import Bottle
from bottle.ext.inject import Plugin

app = Bottle()
injector = app.install(Plugin())

@injector.provider('db')
def get_db_handle():
    return sqlite3.connect('quotes.db').cursor()

@app.route('/random_quote')
def random_quote(db):
    row = db.execute('SELECT quote FROM quotes ORDER BY RANDOM() LIMIT 1').fetchone()
    return row['quote']
```

**Comment by defnull** [comment]
I fixed the example accordingly. This 'install plugins by string' feature does not exist yet ;)
